import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Flysha - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white font-poppins bg-flysha-black">
        {children}
      </body>
    </html>
  );
}
